version: '3'

services:
  app:
    image: ppaquin/docker-volume-cleaner:latest
    environment:
      - USER_SSH=xxx
      - PWD_SSH=xxx
      - HOST_SSH=xxx
    networks:
      - docker-volume-cleaner-network
networks:
  docker-volume-cleaner-network:
#    driver: bridge